const express = require('express');
const router = express.Router();
const Schedule = require('../models/Schedule');
const Notification = require('../models/Notification');
const mongoose = require('mongoose');
const demoSchedule = require('../data/demoSchedule');

// @route   GET api/schedule/:staffId
// @desc    Get schedule by staff ID
router.get('/:staffId', async (req, res) => {
  if (mongoose.connection.readyState !== 1) {
    return res.json(demoSchedule.getAllForStaff(req.params.staffId));
  }

  try {
    const schedules = await Schedule.find({ staffId: req.params.staffId });
    res.json(schedules);
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: 'Server error' });
  }
});

// @route   POST api/schedule/generate
// @desc    Simulate generating an AI schedule
router.post('/generate', async (req, res) => {
  const { staffId } = req.body;
  try {
    if (mongoose.connection.readyState !== 1) {
      return res.json({
        message: 'AI Scheduling optimization completed successfully (demo mode).',
        notification: {
          _id: `demo-notification-${Date.now()}`,
          staffId,
          title: 'New Schedule Generated',
          message: 'Schedule has been regenerated by the AI optimizer.',
          time: 'Just Now',
          read: false,
        },
      });
    }

    // In a real application, this would call the AI scheduler algorithm.
    // For now, we simulate success and add a notification.
    const notification = new Notification({
      staffId,
      title: 'New Schedule Generated',
      message: 'Schedule for May 2024 has been re-generated by AI optimizer.',
      time: 'Just Now',
    });
    await notification.save();

    res.json({ message: 'AI Scheduling optimization completed successfully.', notification });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: 'Server error' });
  }
});

module.exports = router;
